name: Build Vue App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v3

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # или нужная версия

      # 3. Устанавливаем зависимости
      - run: npm install

      # 4. Собираем продакшн-билд
      - run: npm run build

      # 5. Пушим dist в отдельную ветку (например, gh-pages)
      - name: Push Build to gh-pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build # можешь назвать gh-pages или build
